before:
  hooks:
    - go mod vendor
    - go mod tidy
release:
  github:
    owner: andrewrech
    name: polly
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
universal_binaries:
  - replace: true
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - "*md"
signs:
  -
    artifacts: all
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
