builds:
- env:
  - CGO_ENABLED=0
  goos:
    - freebsd
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
signs:
- artifacts: all
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
